let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCgj2C45UitUBsuAMDxjLD8yIBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SHIPYARD = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"SHIPYARD", type text}})
in
    #"Changed Type"
