let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8nM1MFCK1YlWcnGBMoIdYYwgKMMZxgjyhUk5w6RgDN8AmEg4lBEKNjAWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Key Events for Undocking" = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Key Events for Undocking", type text}})
in
    #"Changed Type"
