let

Source = SharePoint.Files("https://flankspeed.sharepoint-mil.us/sites/NSS-SYWeeklyDailyDrop", [ApiVersion = 15]),
    #"Changed column type 1" = Table.TransformColumnTypes(Source, {{"Date created", type date}}),
    FilterFolderPath = Table.SelectRows(#"Changed column type 1", each Text.EndsWith([Folder Path], "DailyData/Daily Trace/")),
    #"Extracted Text Range" = Table.TransformColumns(FilterFolderPath, {{"Name", each Text.Middle(_, 13, 10), type text}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Extracted Text Range",{{"Name", type date}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", let latest = List.Max(#"Changed Type1"[Name]) in each [Name] = latest),
    #"Filter Hidden Files" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function" =  Table.AddColumn(#"Filter Hidden Files", "Trace Files Transform file", each Table.PromoteHeaders(Excel.Workbook([Content], null, true){0}[Data], [PromoteAllScalars=true])),
    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Invoke Custom Function", {"Trace Files Transform file"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Removed Errors1",{"Trace Files Transform file"}),
    #"Expanded Trace Files Transform file" = Table.ExpandTableColumn(#"Removed Other Columns", "Trace Files Transform file", {"ICN/KO", "WORKING STATUS", "ACTUAL START DATE", "ACTUAL COMPLETE DATE", "WORK TYPE", "ZONE MANAGER", "NAME", "SHOP CODE", "CALENDAR CODE", "STATUS SET DATE", "PROJ ID", "CURRENT START DATE", "CURRENT COMPLETION DATE", "TGI TYPE", "DURATION", "CU PHASE APPROVAL STATUS", "SUB-WORK TYPE", "TASK WORK TYPE 'O'", "TASK WORK TYPE 'R'", "TASK WORK TYPE 'M'", "TASK WORK TYPE 'N'", "TASK WORK TYPE 'OM'", "TASK WORK TYPE 'SC'", "% PROGRESS", "LABOR MANHOURS", "KEY EVENT TRACE", "MILESTONE TRACE", "TOTAL FLOAT", "PRIORITY COLOR", "TEST ID", "CU TYPE", "NUCLEAR", "TGI STATUS", "SY PRIORITY NUMBER", "WORK STOPPAGE REASON CODE", "COG CODE", "ESTIMATED RESOLUTION DATE", "SY", "WEEK_START", "DATA_DATE", "RDU_QY", "DAYS_STOPPED_QY", "TGI CODE", "CERT DATE"}, {"ICN/KO", "WORKING STATUS", "ACTUAL START DATE", "ACTUAL COMPLETE DATE", "WORK TYPE", "ZONE MANAGER", "NAME.1", "SHOP CODE", "CALENDAR CODE", "STATUS SET DATE", "PROJ ID", "CURRENT START DATE", "CURRENT COMPLETION DATE", "TGI TYPE", "DURATION", "CU PHASE APPROVAL STATUS", "SUB-WORK TYPE", "TASK WORK TYPE 'O'", "TASK WORK TYPE 'R'", "TASK WORK TYPE 'M'", "TASK WORK TYPE 'N'", "TASK WORK TYPE 'OM'", "TASK WORK TYPE 'SC'", "% PROGRESS", "LABOR MANHOURS", "KEY EVENT TRACE", "MILESTONE TRACE", "TOTAL FLOAT", "PRIORITY COLOR", "TEST ID", "CU TYPE", "NUCLEAR", "TGI STATUS", "SY PRIORITY NUMBER", "WORK STOPPAGE REASON CODE", "COG CODE", "ESTIMATED RESOLUTION DATE", "SY", "WEEK_START", "DATA_DATE", "RDU_QY", "DAYS_STOPPED_QY", "TGI CODE", "CERT DATE"}),
    #"Removed blank rows" = Table.SelectRows(#"Expanded Trace Files Transform file", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed blank rows", "DATA DATE WEEK OF YEAR", each Date.WeekOfYear([DATA_DATE])), {{"DATA DATE WEEK OF YEAR", Int64.Type}}),
    #"Added custom 1" = Table.TransformColumnTypes(Table.AddColumn(#"Added custom", "DATA DATE DAY OF WEEK", each Date.DayOfWeek([DATA_DATE], Day.Monday)), {{"DATA DATE DAY OF WEEK", Int64.Type}}),
    #"Changed column type" = Table.TransformColumnTypes(#"Added custom 1", {{"DATA_DATE", type datetime}}),
    #"Replaced value" = Table.ReplaceValue(#"Changed column type", "", null, Replacer.ReplaceValue, {"KEY EVENT TRACE"}),

    #"Changed Type" = Table.TransformColumnTypes(#"Replaced value",{{"DATA_DATE", type date}}),
    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Removed Duplicates" = Table.Distinct(#"Removed Blank Rows"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Duplicates",{{"ICN/KO", type text}, {"WORKING STATUS", type text}, {"ACTUAL START DATE", type date}, {"ACTUAL COMPLETE DATE", type date}, {"WORK TYPE", type text}, {"ZONE MANAGER", type text}, {"NAME.1", type text}, {"SHOP CODE", type text}, {"CALENDAR CODE", type text}, {"STATUS SET DATE", type date}, {"PROJ ID", type text}, {"CURRENT START DATE", type date}, {"CURRENT COMPLETION DATE", type date}, {"TGI TYPE", type text}, {"DURATION", Int64.Type}, {"CU PHASE APPROVAL STATUS", type text}, {"SUB-WORK TYPE", type text}, {"TASK WORK TYPE 'O'", Int64.Type}, {"TASK WORK TYPE 'R'", Int64.Type}, {"TASK WORK TYPE 'M'", Int64.Type}, {"TASK WORK TYPE 'N'", Int64.Type}, {"TASK WORK TYPE 'OM'", Int64.Type}, {"TASK WORK TYPE 'SC'", Int64.Type}, {"% PROGRESS", Int64.Type}, {"LABOR MANHOURS", type number}, {"KEY EVENT TRACE", type text}, {"MILESTONE TRACE", type text}, {"TOTAL FLOAT", Int64.Type}, {"PRIORITY COLOR", type text}, {"TEST ID", type text}, {"CU TYPE", type text}, {"NUCLEAR", type text}, {"TGI STATUS", type text}, {"SY PRIORITY NUMBER", Int64.Type}, {"WORK STOPPAGE REASON CODE", type text}, {"COG CODE", type text}, {"ESTIMATED RESOLUTION DATE", type date}, {"SY", type text}, {"WEEK_START", type date}, {"DATA_DATE", type date}, {"RDU_QY", Int64.Type}, {"DAYS_STOPPED_QY", type number}, {"TGI CODE", type text}, {"CERT DATE", type date}, {"DATA DATE WEEK OF YEAR", Int64.Type}, {"DATA DATE DAY OF WEEK", Int64.Type}})
in
    #"Changed Type2"
