let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WclSK1YlWcgaTLmDSFUy6gUkPMOkJJr3BpC+YDACTQWAyGEyGgMlQpdhYAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [PHASE = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PHASE", type text}})
in
    #"Changed Type"
