let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WclKK1YlWcgeTQWAyUik2FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"PRIORITY COLOR" = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PRIORITY COLOR", type text}})
in
    #"Changed Type"
